<div class="col-md-8">
    <div class="row">
        <div class="box box-widget">
            <div class="box-header">
                <h3 class="box-title">                    
                    <i class="fa fa-table"></i>
                    <span>Cadastro de projeto</span>                    
                </h3>
            </div> 
            <div class="box-body">
                <h3 class="box-title">                                        
                    Cadastro de projeto realizado com sucesso!                 
                </h3>
            </div>
        </div>
    </div>
</div>