<div class="col-md-8">
    <div class="row">
        <div class="box box-widget">
            <div class="box-header">
                <h3 class="box-title">                    
                    <i class="fa fa-table"></i>
                    <span>Cadastro de projeto - Parte 3</span>                    
                </h3>
            </div> 
            <div class="box-body">
                <form role="form" method="post" action="<?= SITE_URL; ?>/pesquisa/put_in_session/parte3">                    
                    <div class="form-group">
                        <label>Resumo*</label>
                        <textarea name="resumo" class="form-control" rows="6" required="true"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Introdução*</label>
                        <textarea name="introducao" class="form-control" rows="6" required="true"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Justificativa*</label>
                        <textarea name="justificativa" class="form-control" rows="6" required="true"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Objetivo Geral*</label>
                        <textarea name="o_geral" class="form-control" rows="6" required="true"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Objetivo Especifíco*</label>
                        <textarea name="o_especifico" class="form-control" rows="6" required="true"></textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit" name="submit">Próximo</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>