<form action="<?= SITE_URL; ?>/signInAdmin/processar/admin" method="post" >
    <div class="form-group has-feedback">
        <input type="email" name="input-email" class="form-control" placeholder="E-mail" 
               value="" required="true">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>        
    </div>
    <div class="form-group has-feedback">
        <input type="password" name="input-senha" class="form-control" placeholder="Password" required="true">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">      
        <div class="col-xs-4">
            <button type="submit" name="submit" class="btn btn-primary btn-block btn-flat">Login</button>
        </div>        
    </div>
</form>
