<?php
/*
|--------------------------------------------------
|Modal responsável por alterar a senha do usuário.
|--------------------------------------------------
*/
?>
<div class="modal fade" id="keyChange">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php
            /*
            |---------------------------------
            |Cabeçalho do modal
            |---------------------------------
            */
            ?>
            <div class="modal-header" style="background-color:#dd4b39; color: white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">Alterar senha de acesso</h4>
            </div>
            <?php
            /*
            |---------------------------------
            |Corpo do modal
            |---------------------------------
            */
            ?>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="senha-antiga" class="control-label">Senha antiga</label>
                        <input type="password" class="form-control" id="senha-antiga" name="senha-antiga">
                    </div>
                    <div class="form-group">
                        <label for="senha-nova" class="control-label">Senha nova</label>
                        <input type="password" class="form-control" id="senha-nova" name="senha-nova">
                    </div>
                    <div class="form-group">
                        <label for="confirma-senha-nova" class="control-label">Confirma senha nova</label>
                        <input type="password" class="form-control" id="confirma-senha-nova" name="confirma-senha-nova">
                    </div>
                    <div class="form-group">
                        <div id="divchek">
                        </div>
                    </div>
                </form>
            </div>
            <?php
            /*
            |---------------------------------
            |Rodapé do modal
            |---------------------------------
            */
            ?>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="alterar-senha" disabled>Alterar</button>
            </div>
        </div>
    </div>
</div>
<?php
/*
|--------------------------------------------------
|Modal responsável por mudar o status do usuário.
|--------------------------------------------------
*/
?>
<div class="modal fade" id="statusChange">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <?php
            /*
            |---------------------------------
            |Cabeçalho do modal
            |---------------------------------
            */
            ?>
            <div class="modal-header" style="background-color:#dd4b39; color: white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">Alterar status do usuário</h4>
            </div>
            <?php
            /*
            |---------------------------------
            |Corpo do modal
            |---------------------------------
            */
            ?>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                         <div class="checkbox">
                            <label>
                                <input type="checkbox" id="status"> <p id="markcheck"></p>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div id="divchek">
                        </div>
                    </div>                   
                </form>
            </div>
            <?php
            /*
            |---------------------------------
            |Rodapé do modal
            |---------------------------------
            */
            ?>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>
<?php
/*
|--------------------------------------------------
|Modal responsável por reportar um bug.
|--------------------------------------------------
*/
?>
<div class="modal fade" id="sendBug">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php
            /*
            |---------------------------------
            |Cabeçalho do modal
            |---------------------------------
            */
            ?>
            <div class="modal-header" style="background-color:#dd4b39; color: white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">Reportar bug</h4>
            </div>
            <?php
            /*
            |---------------------------------
            |Corpo do modal
            |---------------------------------
            */
            ?>
            <div class="modal-body">
                 <form>                    
                    <div class="form-group">
                        <label for="message-text" class="control-label">Mensagem:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                    <div class="form-group">
                        <div id="divchek">
                        </div>
                    </div> 
                </form>
            </div>
            <?php
            /*
            |---------------------------------
            |Rodapé do modal
            |---------------------------------
            */
            ?>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="reportar-bug" disabled>Enviar</button>               
            </div>
        </div>
    </div>
</div>