<?php
/*
|-----------------------------------------------
|Control Sidebar Principal
|-----------------------------------------------
*/
?>
<aside class="control-sidebar control-sidebar-dark">
    <?php
    /*
    |-----------------------------------------------
    |Create the tabs
    |-----------------------------------------------
    */
    ?>
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">    
        <!--<li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>-->
        <li class="active"><a href="#control-sidebar-settings-tab" data-toggle="tab">
                <i class="fa fa-gears"></i>
            </a>
        </li>
    </ul>
    <?php
    //-----------------------------------------------
    // Tabs
    //-----------------------------------------------
    ?>
    <div class="tab-content">

        <!--<div class="tab-pane" id="control-sidebar-home-tab"></div>-->

        <!--<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>-->

        <?php
        /*
        |-----------------------------------------------
        |Configurações Gerais
        |-----------------------------------------------
        */
        ?>
        <div class="tab-pane active" id="control-sidebar-settings-tab">
            <div class="form-group">                
                <p>
                    <a style="color: white; cursor: pointer" id="key-change">
                        <i class="fa fa-key margin-r-5"></i>
                        <span>Alterar senha</span> 
                    </a>
                </p>
            </div>
            <div class="form-group">                
                <p>
                    <a style="color: white; cursor: pointer" id="status-change">
                        <i class="fa fa-adjust margin-r-5"></i>
                        <span>Alterar status do usuário</span> 
                    </a>
                </p>
            </div>
            <!--<div class="form-group">             
                <p>
                    <a style="color: white; cursor: pointer" id="send-bug">
                        <i class="fa fa-envelope margin-r-5"></i>
                        <span>Reportar bug</span> 
                    </a>
                </p>
            </div>-->
        </div>        
    </div>
</aside>