<header class="main-header">
    <?php
    /*
    |----------------------------------------
    |Nome da rede.
    |----------------------------------------
    */
    ?>
    <a href="<?= SITE_URL; ?>/index" class="logo">
        <span class="logo-mini"><b>S</b></span>                
        <span class="logo-lg"><b>SOCIALMEDIA</b></span>
    </a> 
    <nav class="navbar navbar-static-top">
        <?php
        /*
        |---------------------------------
        |Sidebar toggle button.
        |---------------------------------
        */
        ?>        
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">                
                <?php
                //Messages: style can be found in dropdown.less
                /*
                |-----------------------------------------------<-notifications.js
                |Carrega o menu de notificações.
                |-----------------------------------------------
                */
                $this->loadView("software/socialmedia/index/parts/general/notifications");
                /*
                |-----------------------------------------------
                |Carrega o user menu.
                |-----------------------------------------------
                */
                $this->loadView("software/socialmedia/index/parts/general/user_menu");
                ?>
                <?php
                /*
                |-----------------------------------------
                |Chama o menu do chat e de configurações
                |-----------------------------------------
                */
                ?>                              
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-plus"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>