<?php
/*
|------------------------------------------------
|Aqui vão as mensagens.
|------------------------------------------------
*/
?>
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <span class="label label-success" id="mensagens_recebidas"></span>
    </a>    
    <ul class="dropdown-menu">
        <?php
        /*
        |--------------------------------------
        |Diz quantas novas mensagens existem.
        |--------------------------------------
        */
        ?>
        <li class="header" id="message_notificacao"></li>
        <li>
            <?php
            /*
            |===================================================|
            |===================================================|
            |=============Container das mensagens===============|
            |===================================================|
            |===================================================V
            */
            ?>
            <ul class="menu" id="message_notificacao_in">
                <?php
                /*
                |----------------------
                |Início da mensagem.
                |----------------------
                */
                ?>
                <!--<li>
                    <a href="#">
                        <div class="pull-left">
                            <img id="img_message" class="img-circle">
                        </div>
                        <h4>
                            <span id="message_nome"></span>
                        </h4>
                        <p>Entrou em contato com você pelo chat.</p>
                    </a>
                </li>-->
                <?php
                /*
                |----------------------
                |Fim da mensagem.
                |----------------------
                */
                ?>
            </ul>
            <?php
            /*
            |===================================================^
            |===================================================|
            |=============Container das mensagens===============|
            |===================================================|
            |===================================================|
            */
            ?>
        </li>
        <li class="footer"><a href="#">Ir para o chat</a></li>
    </ul>    
</li>
<?php
/*
|------------------------------------------------
|Aqui vão as notificações.
|------------------------------------------------
*/
?>    
<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <span class="label label-warning" id="convites_recebidos"></span>
    </a>
    <ul class="dropdown-menu" id="menu_notification_rec">
        <li class="header" id="convites_recebidos_text"></li>
        <li>
            <?php
            /*
            |===================================================|
            |===================================================|
            |=============Container das mensagens===============|
            |===================================================|
            |===================================================V
            */
            ?>
            <ul class="menu" id="convite_notificacao">
                                            
            </ul>
            <?php
            /*
            |===================================================^
            |===================================================|
            |=============Container das mensagens===============|
            |===================================================|
            |===================================================|
            */
            ?>
        </li>
        <li class="footer">
            <a href="<?= SITE_URL; ?>/sol/">Ir para solicitações</a>
        </li>
    </ul>
</li>
<?php
/*
|------------------------------------------------
|Aqui vão as tarefas.
|------------------------------------------------
*/
?>
<?php
// <li class="dropdown tasks-menu">
//     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
//         <i class="fa fa-flag-o"></i>
//         <span class="label label-danger">9</span>
//     </a>
//     <ul class="dropdown-menu">
//         <li class="header">You have 9 tasks</li>
//         <li>
//             <!-- inner menu: contains the actual data -->
//             <ul class="menu">
//                 <li><!-- Task item -->
//                     <a href="#">
//                         <h3>
//                             Design some buttons
//                             <small class="pull-right">20%</small>
//                         </h3>
//                         <div class="progress xs">
//                             <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
//                                 <span class="sr-only">20% Complete</span>
//                             </div>
//                         </div>
//                     </a>
//                 </li>
//                 <!-- end task item -->
//                 <li><!-- Task item -->
//                     <a href="#">
//                         <h3>
//                             Create a nice theme
//                             <small class="pull-right">40%</small>
//                         </h3>
//                         <div class="progress xs">
//                             <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
//                                 <span class="sr-only">40% Complete</span>
//                             </div>
//                         </div>
//                     </a>
//                 </li>
//                 <!-- end task item -->
//                 <li><!-- Task item -->
//                     <a href="#">
//                         <h3>
//                             Some task I need to do
//                             <small class="pull-right">60%</small>
//                         </h3>
//                         <div class="progress xs">
//                             <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
//                                 <span class="sr-only">60% Complete</span>
//                             </div>
//                         </div>
//                     </a>
//                 </li>
//                 <!-- end task item -->
//                 <li><!-- Task item -->
//                     <a href="#">
//                         <h3>
//                             Make beautiful transitions
//                             <small class="pull-right">80%</small>
//                         </h3>
//                         <div class="progress xs">
//                             <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
//                                 <span class="sr-only">80% Complete</span>
//                             </div>
//                         </div>
//                     </a>
//                 </li>
//                 <!-- end task item -->
//             </ul>
//         </li>
//         <li class="footer">
//             <a href="#">View all tasks</a>
//         </li>
//     </ul>
// </li>
?>