<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img id="img_sidebar" class="img-circle">
            </div>
            <div class="pull-left info">
                <p id="nome_sobrenome_sidebar"></p>
                <a id="status_sidebar" style="cursor: pointer">
                </a>
            </div>
        </div>

        <?php
        /*
        |-----------------------------------------------
        | Realiza uma busca por um determinado usuário!
        |-----------------------------------------------
        */
        ?>
        <form id="form-search" action="<?= SITE_URL; ?>/usuario/searchUser/" method="post" class="sidebar-form">
            <div class="input-group">
                <input type="text"
                class="form-control"
                placeholder="Pesquisar..."
                id="busca"
                value="">

                <span class="input-group-btn">
            		<button type="submit" class="btn btn-flat btn-pesquisar">
                	<i class="fa fa-search"></i>
            	</button>
        </span>
            </div>
        </form>

<!--        <ul class="sidebar-menu">
          <li>
              <a style="cursor:pointer" id="btn-search-advanced">
                  <i class="fa fa-search"></i>
                  <span>Busca avançada</span>
              </a>
          </li>
        </ul>-->

        <ul class="sidebar-menu">
            <li class="header">MENU DE NAVEGAÇÃO</li>
            <li>
                <a href="<?= SITE_URL; ?>/relationships">
                    <i class="fa fa-group"></i>
                    <span>Relações</span>
                </a>
            </li>
            <li>
                <a href="<?= SITE_URL; ?>/sol">
                    <i class="fa  fa-paper-plane"></i>
                    <span>Solicitações</span>
                </a>
            </li>
            <li>
                <a href="<?= SITE_URL; ?>/chat">
                    <i class="fa  fa-paper-plane"></i>
                    <span>Chat</span>
                </a>
            </li>
<!--            <li>
                <a href="<?= SITE_URL; ?>/ed2">
                    <i class="fa  fa-graduation-cap"></i>
                    <span>Educacional</span>
                </a>
            </li>-->
<!--            <li>
                <a href="<?= SITE_URL; ?>/cfinances">
                    <i class="fa  fa-graduation-cap"></i>
                    <span>Cfinances</span>
                </a>
            </li>-->
        </ul>
    </section>
</aside>
