<div class="col-md-3">
    <div class="info-box bg-yellow">
        <span class="info-box-icon"><i class="fa fa-book"></i></span>
        <div class="info-box-content">
            <a href="<?= SITE_URL; ?>/EdAdmin/addConteudo/"
            role="button"
            style="color: white"><h4>Adicionar Conteúdo</h4></a>
        </div>
    </div>
    <div class="info-box bg-blue">
        <span class="info-box-icon"><i class="fa fa-users"></i></span>
        <div class="info-box-content">
            <a href="<?= SITE_URL; ?>/EdAdmin/addCategoria/"
            role="button"
            style="color: white"><h4>Adicionar Categoria</h4></a>
        </div>
    </div>
    <div class="info-box bg-yellow">
        <span class="info-box-icon"><i class="fa fa-money"></i></span>
        <div class="info-box-content">
            <a href="<?= SITE_URL; ?>/EdAdmin/listConteudo/"
            role="button" style="color: white"><h4>Listar Conteúdo</h4>
            </a>
        </div>
    </div>
    <div class="info-box bg-blue">
        <span class="info-box-icon"><i class="fa fa-money"></i></span>
        <div class="info-box-content">
            <a href="<?= SITE_URL; ?>/EdAdmin/listarCategorias/" 
            role="button" style="color: white"><h4>Listar Categorias</h4>
            </a>
        </div>
    </div>
</div>
