<?php
/*
|-----------------------------------------------
|Início do bloco que carrega a mensagem de erro.
|-----------------------------------------------
*/
?>
<div class="row">
    <?php if (Geekx\Session::get("erro_update")): ?>
        <div class="col-md-9">
            <div class="box box-widget widget-user">
                <div class="alert alert-warning alert-dismissible">
                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                    <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
                    <?= Geekx\Session::get("erro_update"); ?>
                </div>
            </div>
        </div>

    <?php elseif (Geekx\Session::get("categoria_sucesso")): ?>
        <div class="col-md-9">
            <div class="box box-widget widget-user">
                <div class="alert alert-success alert-dismissible">
                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                    <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
                    <?= Geekx\Session::get("categoria_sucesso"); ?>
                </div>
            </div>
        </div>
    <?php else: ?>
    <?php endif; ?>
    <?php
    /*
    |-----------------------------------------------
    |Fim do bloco que carrega a mensagem de erro.
    |-----------------------------------------------
    */
    ?>
    <div class="col-md-6">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Adicionar Conteúdo</h3>
            </div>
            <form role="form" action="<?= SITE_URL; ?>/EdAdmin/adicionaCategoria/" method="post">
                <div class="box-body">
                     <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Categoria:</label>
                                <input class="form-control" name="categoria"
                                       type="text" value="" required="true">
                            </div>
                            <div class="form-group">
                                <label>Descrição</label>
                                <textarea name="descricao" rows="3"
                                class="form-control" required="true"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" name="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
    <?php
    /*
    |----------------------------------------
    |Submenu de edição.----------------------
    |----------------------------------------
    */
    ?>
    <?php $this->loadView("admin/educacional/buttons"); ?>
 </div>

 <?php if (Geekx\Session::get("add_categoria")): ?>
     <?php Geekx\Session::delete("add_categoria"); ?>
 <?php endif; ?>
