<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Listagem de categorias</h3>
            </div>
            <div class="box-body">
                <table id="users" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>ID</th>
                          <th>Categoria</th>
                          <th>Descrição</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($categorias as $categoria) : ?>
                        <tr>
                            <td><?= $categoria["id"]; ?></td>
                            <td><?= $categoria["categoria"]; ?></td>
                            <td>
                                <textarea rows="4" class="form-control">
                                    <?= $categoria["descricao"]; ?>
                                </textarea>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                          <th>ID</th>
                          <th>Categoria</th>
                          <th>Descrição</th>
                          <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<?php if (Geekx\Session::get("listaCategorias")): ?>
    <?php Geekx\Session::delete("listaCategorias"); ?>
<?php endif; ?>
