<!DOCTYPE html>
<html lang="en">
    <?php $this->loadView("homes/home_second/partes/head"); ?>
    <body>
        <div class="preloader">
            <div class="preloder-wrap">
                <div class="preloder-inner"> 
                    <div class="ball"></div> 
                    <div class="ball"></div> 
                    <div class="ball"></div> 
                    <div class="ball"></div> 
                    <div class="ball"></div> 
                    <div class="ball"></div> 
                    <div class="ball"></div>
                </div>
            </div>
        </div>

        <?php $this->loadView("homes/home_second/partes/header"); ?>
        <?php $this->loadView("homes/home_second/partes/carousel"); ?>
        <?php $this->loadView("homes/home_second/partes/about"); ?>        
        <?php $this->loadView("homes/home_second/partes/services"); ?>        
        <?php
        //$this->loadView("homes/home_second/partes/team"); 
        ?>        
        <?php $this->loadView("homes/home_second/partes/portifolio"); ?>        
        <?php
        //$this->loadView("homes/home_second/partes/clients"); 
        ?>        
        <?php 
        
//        $this->loadView("homes/home_second/partes/blog"); 
        
        ?>        
        <?php $this->loadView("homes/home_second/partes/contact"); ?>        
        <?php $this->loadView("homes/home_second/partes/footer"); ?>       

        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/jquery.js"></script> 
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/smoothscroll.js"></script> 
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/jquery.isotope.min.js"></script>
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/jquery.prettyPhoto.js"></script> 
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/jquery.parallax.js"></script> 
        <script type="text/javascript" src="<?= HOME_SECOND ?>/js/main.js"></script> 
    </body>
</html>