<section id="about-us">
    <div class="container">
<!--        <div class="text-center">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">Sobre nós</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing 
                    elit, sed diam nonummy nibh euismod 
                    tincidunt ut laoreet dolore magna 
                    aliquam erat volutpat. Ut wisi enim 
                    ad minim veniam, quis nostrud exerci 
                    tation ullamcorper suscipit lobortis 
                    nisl ut aliquip ex ea commodo consequat.</p>
            </div>
        </div>-->
        <div class="about-us">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Why with us?</h3>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#about" data-toggle="tab"><i class="fa fa-lightbulb-o"></i> Estratégia</a></li>
                        <li><a href="#mission" data-toggle="tab"><i class="fa fa-th-large"></i> Plano</a></li>
<!--                        <li><a href="#community" data-toggle="tab"><i class="fa fa-users"></i> Community</a></li>-->
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="about">
                            <div class="media">
                                <img class="pull-left media-object" src="<?= HOME_SECOND ?>/images/about-us/about.jpg" alt="about us"> 
                                <div class="media-body">
                                    <p>Nossa estratégia diz respeito a fomentar o engajamento com aspectos fundamentais do mercado financeiro.</p>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="mission">
                            <div class="media">
                                <img class="pull-left media-object" src="<?= HOME_SECOND ?>/images/about-us/mission.jpg" alt="Mission"> 
                                <div class="media-body">
                                    <p>Diz respeito a produzir a maior quantidade de conteúdo sobre finanças acessível ao público.</p>
                                </div>
                            </div>
                        </div>
<!--                        <div class="tab-pane fade" id="community">
                            <div class="media">
                                <img class="pull-left media-object" src="<?= HOME_SECOND ?>/images/about-us/community.jpg" alt="Community"> 
                                <div class="media-body">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. </p>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>
                <div class="col-sm-6">
                    <h3>Skills</h3>
                    <div class="skill-bar">
                        <div class="skillbar clearfix " data-percent="90%">
                            <div class="skillbar-title">
                                <span>Tesouro Direto</span>
                            </div>
                            <div class="skillbar-bar"></div>
                            <div class="skill-bar-percent">90%</div>
                        </div> <!-- End Skill Bar -->
                        <div class="skillbar clearfix" data-percent="40%">
                            <div class="skillbar-title"><span>Social Finances</span></div>
                            <div class="skillbar-bar"></div>
                            <div class="skill-bar-percent">40%</div>
                        </div> <!-- End Skill Bar -->
                        <div class="skillbar clearfix " data-percent="30%">
                            <div class="skillbar-title"><span>Negócios</span></div>
                            <div class="skillbar-bar"></div>
                            <div class="skill-bar-percent">30%</div>
                        </div> <!-- End Skill Bar -->
                        <div class="skillbar clearfix " data-percent="30%">
                            <div class="skillbar-title"><span>Finanças</span></div>
                            <div class="skillbar-bar"></div>
                            <div class="skill-bar-percent">30%</div>
                        </div> <!-- End Skill Bar -->
                        
                        <div class="skillbar clearfix " data-percent="20%">
                            <div class="skillbar-title"><span>Renda Variável</span></div>
                            <div class="skillbar-bar"></div>
                            <div class="skill-bar-percent">10%</div>
                        </div> <!-- End Skill Bar --></div>
                </div>
            </div>
        </div>
    </div>
</section><!--/#about-us-->