<section id="home">
    <div class="home-pattern"></div>
    <div id="main-carousel" class="carousel slide" data-ride="carousel"> 
        <ol class="carousel-indicators">
            <li data-target="#main-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#main-carousel" data-slide-to="1"></li>
            <li data-target="#main-carousel" data-slide-to="2"></li>
        </ol><!--/.carousel-indicators--> 
        <div class="carousel-inner">
            <div class="item active" style="background-image: url(<?= HOME_SECOND ?>/images/slider/slide3.jpg)"> 
                <div class="carousel-caption"> 
                    <div> 
                        <h2 class="heading animated bounceInDown">Encontre outros investidores</h2> 
                        <p class="animated bounceInUp">Conheça nosso ambiente social clicando abaixo</p> 
                        <a class="btn btn-default slider-btn animated fadeIn" href="http://localhost/mindmon$/login" target="_blank">Started Social</a> 
                    </div> 
                </div> 
            </div>
            <div class="item" style="background-image: url(<?= HOME_SECOND ?>/images/slider/slide2.jpg)"> 
                <div class="carousel-caption"> <div> 
                        <h2 class="heading animated bounceInDown" style="color: #fc7700">Gerencie bem seu negócio e aumente seus lucros</h2> 
                        <p class="animated bounceInUp" style="color: #000">Conheça o Blue Line clicando abaixo</p> 
                        <a class="btn btn-default slider-btn animated fadeIn" href="http://localhost/mindmon$/bluelinelogin" target="_blank">Get Started</a> 
                    </div> 
                </div> 
            </div> 
            <div class="item" style="background-image: url(<?= HOME_SECOND ?>/images/slider/slide1.jpg)"> 
                <div class="carousel-caption"> 
                    <div> 
                        <h2 class="heading animated bounceInRight">Mantenha-se atualizado em nosso blog</h2> 
                        <p class="animated bounceInLeft">Notícias reelevantes em apenas um clique</p> 
                        <a class="btn btn-default slider-btn animated bounceInUp" href="http://localhost/mindmon$/blog" target="_blank">Get Started</a> 
                    </div> 
                </div> 
            </div>
        </div><!--/.carousel-inner-->

        <a class="carousel-left member-carousel-control hidden-xs" href="#main-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
        <a class="carousel-right member-carousel-control hidden-xs" href="#main-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
    </div> 

</section><!--/#home-->