<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading" style="padding-bottom: 0px">
                    <h2 class="title-one">Contato</h2>
                    <p>Sempre apostos a te responder de forma eficiente.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="pattern"></div>
            <div class="row text-center clearfix">
                <div class="col-sm-12">
                    <div class="contact-address">
                        <address>
                            <p><span>E-</span>mail's</p>
                            <strong>capitalfuturo@club.com<br>capitalfuturo.parcerias@club.com<br> capitalfuturo.sugestoes@club.com</strong><br>
                            <small>( Ou entre em contato nas redes sociais.)</small></address>
                        <div class="social-icons">
                            <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
<!--                <div class="col-sm-6"> 
                    <div id="contact-form-section">
                        <div class="status alert alert-success" style="display: none"></div>
                        <form id="contact-form" class="contact" name="contact-form" method="post" action="send-mail.php">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control name-field" required="required" placeholder="Your Name"></div>
                            <div class="form-group">
                                <input type="email" name="email" class="form-control mail-field" required="required" placeholder="Your Email">
                            </div> 
                            <div class="form-group">
                                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Message"></textarea>
                            </div> 
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </form> 
                    </div>
                </div>-->
            </div>
        </div>
    </div> 
</section> <!--/#contact--> 