<head> 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Creative One Page Parallax Template">
    <meta name="keywords" content="Creative, Onepage, Parallax, HTML5, Bootstrap, Popular, custom, personal, portfolio" /> 
    <meta name="author" content=""> 
    <title>Capital|Futuro</title> 
    <!--<script src="https://use.fontawesome.com/b7ea8a38db.js"></script>-->

    <link href="<?= HOME_SECOND ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= HOME_SECOND ?>/css/prettyPhoto.css" rel="stylesheet"> 
    <!--<link href="<?= HOME_SECOND ?>/css/font-awesome.min.css" rel="stylesheet">--> 
    <link href="<?= HOME_SECOND ?>/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet"> 
    <link href="<?= HOME_SECOND ?>/css/animate.css" rel="stylesheet"> 
    <link href="<?= HOME_SECOND ?>/css/main.css" rel="stylesheet">
    <link href="<?= HOME_SECOND ?>/css/responsive.css" rel="stylesheet"> 
    <!--[if lt IE 9]> <script src="js/html5shiv.js"></script> 
    <script src="js/respond.min.js"></script> <![endif]--> 
    
    <!--<link rel="shortcut icon" href="<?= HOME_SECOND ?>/images/ico/favicon.png">--> 
    <!--<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= HOME_SECOND ?>/images/ico/apple-touch-icon-144-precomposed.png"> 
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= HOME_SECOND ?>/images/ico/apple-touch-icon-114-precomposed.png"> 
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?= HOME_SECOND ?>/images/ico/apple-touch-icon-72-precomposed.png"> 
    <link rel="apple-touch-icon-precomposed" href="<?= HOME_SECOND ?>/images/ico/apple-touch-icon-57-precomposed.png">-->
</head>