<section id="portfolio">
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">Materiais publicados</h2>
                <p>Veja alguns de nossos materiais publicados.</p>
            </div>
        </div>
        <ul class="portfolio-filter text-center">
            <li><a class="btn btn-default active" href="#" data-filter="*">Tudo</a></li>
<!--            <li><a class="btn btn-default" href="#" data-filter=".html">Html</a></li>
            <li><a class="btn btn-default" href="#" data-filter=".wordpress">Wordpress</a></li>
            <li><a class="btn btn-default" href="#" data-filter=".joomla">Joomla</a></li>
            <li><a class="btn btn-default" href="#" data-filter=".megento">Megento</a></li>-->
        </ul><!--/#portfolio-filter-->
        <div class="portfolio-items">
            <div class="col-sm-3 col-xs-12 portfolio-item html">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/1.jpg" alt=""></div> 
                    <div class="mask text-center">
                        <h3>Conhecendo Debêntures</h3>
                        <h5>Conheça alguns dos principais conceitos envolvidos nesse tipo de investimento.</h5>
                        <a href="https://docs.google.com/presentation/d/1rkjpb147wcEtqbSZtawxRI4jBquyYFbnCw3dMZQ3Atw/edit?usp=sharing" target="_blank"><i class="fa fa-link"></i></a>
                        <!--<a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>-->
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item jooma">
                <div class="view efffect" >
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/2.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>Ações Fundamentos</h3>
                        <h4>Comece como os principais conceitos.</h4>
                        <a href="https://docs.google.com/presentation/d/1aCDnMk4rUMY5_5LERm2thCaewff56POvOaC5MUXDP_M/edit?usp=sharing" target="_blank"><i class="fa fa-link"></i></a>
                        <!--<a href="<?= HOME_SECOND ?>/images/portfolio/big-item4.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>-->
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item wordpress">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/3.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>TED vs DOC</h3>
                        <h4>Esse tema é essêncial para quem investe.</h4>
                        <a href="https://docs.google.com/presentation/d/1guEhxBFvepOpO4r__Q52gkV4x0sQo6gEu-sA2sT5bc8/edit?usp=sharing" target="_blank"><i class="fa fa-link"></i></a>
                        <!--<a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>-->
                    </div>
                </div>
            </div>
<!--            <div class="col-sm-3 col-xs-12 portfolio-item megento">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/4.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item html">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/5.jpg" alt="">
                    </div> <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item wordpress">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/6.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item html">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/7.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item joomla">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/8.jpg" alt=""></div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item html">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/9.jpg" alt="">
                    </div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item wordpress">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/10.jpg" alt=""></div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item joomla">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/11.jpg" alt=""></div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item3.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 portfolio-item megento">
                <div class="view efffect">
                    <div class="portfolio-image">
                        <img src="<?= HOME_SECOND ?>/images/portfolio/12.jpg" alt=""></div> 
                    <div class="mask text-center">
                        <h3>Novel</h3>
                        <h4>Lorem ipsum dolor sit amet consectetur</h4>
                        <a href="#"><i class="fa fa-link"></i></a>
                        <a href="<?= HOME_SECOND ?>/images/portfolio/big-item4.jpg" data-gallery="prettyPhoto"><i class="fa fa-search-plus"></i></a>
                    </div>
                </div>
            </div>-->
        </div>
    </div> 

</section> <!--/#portfolio-->