<section id="services" class="parallax-section">
            <div class="container">
                <div class="row text-center">
                    <div class="col-sm-8 col-sm-offset-2">
                        <h2 class="title-one">Serviços Básicos</h2>
                        <p>Nossos serviços básicos atualmente envolvem diretamento o uso de nossos softwares para ajudar você a genrenciar seus negócios, suas finanças, bem como pôr você em contato com pessoas que poderam ajudar você de aluma forma a evoluir seus négois.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="our-service">
                            <div class="services row">
                                <div class="col-sm-4">
                                    <div class="single-service">
                                        <i class="fa fa-users"></i>
                                        <h2>Capital|Futuro Social</h2>
                                        <p>Trata-se de um ambiente social para investidores, prático e simples para quem quer encontrar pessoas interessadas no mundo dos investimentos.</p>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="single-service">
                                        <i class="fa fa-gears"></i>
                                        <h2>Blue|Line</h2>
                                        <p>É o nosso MiniERP, criado para desmpenhar funções básicas de gerenciamento de seu negócio, propiciando a você flexibilidade para no que diz respeito a aquisição de módulos pontuais, adequados a necessidade do seu negócio.</p>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="single-service">
                                        <i class="fa fa-envelope"></i>
                                        <h2>Blog Capital|Futuro</h2>
                                        <p>Aqui são postadas informações sobre atualizações de softwares, notícias e nossos tutoriais eventuais.</p>
                                    </div>
                                </div></div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!--/#service-->