<div class="container">
    <div class="navbar-header">
        <button type="button" 
                class="navbar-toggle collapsed"
                data-toggle="collapse" 
                data-target="#navbar" 
                aria-expanded="false"
                aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span> <span
                class="icon-bar"></span> <span class="icon-bar"></span> <span
                class="icon-bar">
            </span>
        </button>                            
        <a href="<?= SITE_URL; ?>">
            <img src="<?= STATIC_URL ?>/img/LogoSocialMedia.png"/>
        </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">                            
        <form class="navbar-form navbar-right" method="post" action="<?= SITE_URL; ?>/login/processar">
            <div class="form-group">
                <input type="text" name="input-email" placeholder="E-mail"
                        class="form-control" id="email-login" required="true">
            </div>
            <div class="form-group">
                <input type="password" name="input-senha" placeholder="Password"
                        class="form-control" id="senha-login" required="true">
            </div>
            <button type="submit" name="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>