<div class="row clearfix">
    <div class="col-md-12 column">
        <h3 style="margin-bottom: 20px; margin-top: 0px">
            <strong>Política de Dados</strong>
        </h3>                    
        <p id="texto_justificado">          
            Esta política descreve quais informações coletamos e 
            como as utilizamos e compartilhamos.            
        </p>
        <hr/>
        <p id="texto_justificado">            
            Ao analisar a nossa política, lembre-se de que ela se aplica a todas 
            as marcas, produtos e serviços vinculados. 
        </p>
        <hr/>
        <p id="texto_justificado">            
            Os dados recolhidos de você dizem respeito as suas relações 
            diretas, como por exemplo, quem você convidou, com que 
            frequência acessa a rede e preferências de investimento. Esses dados são usados 
            para melhorar sua experiência de usuário, bem como sua interação com outros 
            usuários. Não temos o objetivo de ser invasivos demais, alías essa é uma 
            prática combatida por nós.
            Queremos que você sinta e constate que respeitamos sua privacidade e levamos isso 
            muito a sério. Embora garantir que um ambiente desses funcione sem o uso dessas informações 
            para que possamos nos manter com publicidades seja difícil, faremos o máximo para evitar 
            usar seus dados para lhe oferecer publicidade direcionada em momentos inoportunos. 
            Nosso ambiente foca em formas de ganho menos invasivas, mas atua para que o mesmo seja
            suficiente às demandas de infra-estrutura da plataforma.
        </p>
        <hr/>
        <h3 style="margin-bottom: 20px; margin-top: 0px">
            <strong>Do criador do serviço para você usuário</strong>
        </h3>
        <p id="texto_justificado">            
            Essa política de dados é minha forma pessoal de lidar com suas informações, 
            de modo que eu sempre estarei envolvido diretamente com ela para garantir que você 
            não se decipicione com a forma como lidamos com suas informações. Estarei sempre trabalhando para que 
            nossa relação seja de amizade sincera, não quero que seus dados sejam usados inadivertidamente, ou que 
            você seja perturbado por publicidade indesejada inoportunamente, ou qualquer outra forma de perturbação na CapitalFuturo. 
            Quero acima de tudo que nossa relação seja duradoura e boa para ambas as partes.
        </p>
        <hr/>
        <!--<p id="texto_justificado">            
            Atenciosamente, Victor Porto.
        </p>-->
    </div>  
</div>