<div class="row clearfix">
    <div class="col-md-12 column">
        <h3 style="margin-top: 0px; padding-top: 0px; text-align: center;margin-bottom: 20px;">
            <strong>Aos usuários</strong>
        </h3>
        <p id="texto_justificado">
            Nosso objetivo é fornecer a você usuário, recursos 
            capazes de facilitar a reunião de pessoas e 
            informações em torno de um tema que está se tornando 
            cada vez mais frequente entre os brasileiros, estamos falando 
            de investimentos, principalmente em uma conjuntura social onde a aposentadoria 
            tende a acontecer mais tarde. Conhecer as pessoas certas e ter a segurança necessária
            para interagir com elas é fundamental para o ímpeto do investidor se manter constante. 
            Nossa proposta é criar o ambiente necessário para que seu ímpeto de investidor esteja sempre 
            aceso.
        </p>
    </div>  
</div>
