<div class="row clearfix">
    <div class="col-md-12 column">
        <h3 style="margin-bottom: 20px; margin-top: 0px">
            <strong>Termos de Uso</strong>
        </h3>
        <p id="texto_justificado">
            O idioma da versão original deste acordo é o Português
            aceito nos países que aderiram ao <strong>Acordo Ortográfico 
            da Língua Portuguesa</strong>. Desta forma, esta será 
            sempre a versão que prevalecerá independente de qualquer outra tradução. 
            No momento em que você lê este acordo a utilização desse ambiente 
            não está prevista em países que não aderiram ao acordo ortográfico
            citado acima. De modo que se você optar por se cadastrar em nosso ambiente, tenha em mente 
            que não está amparado por este acordo de termos, bem como pelos 
            nossos mecanismos de gerenciamento de dados para resguardá-lo de interações 
            perniciosas e problemáticas, ou seja, é por sua conta e risco.
        </p>       
        <h3 style="margin-bottom: 20px;">
            <strong>Declaração de Direitos e Responsabilidades para Usuários</strong>
        </h3>
        <p id="texto_justificado">
            Ao usar ou acessar a rede CapitalFuturo, você concorda com esta <strong>Declaração</strong>, conforme a mesma é atualizada 
            periodicamente de acordo com as necessidades de evolução do serviço.
        </p>
    </div>  
</div>
<hr/>
<div class="row clearfix">
    <div class="col-md-12 column">          
        <h3 style="margin-bottom: 20px;">
            <strong>1. Segurança para Usuários</strong>
        </h3>           
        <p id="texto_justificado">
            A CapitalFuturo foi criada para ser uma rede social de apoio a investidores, 
            de modo que quaisquer conteúdos que vão de encontro a filosofia da CapitalFuturo não serão permitidos 
            sob nenhuma circusntância. Esperamos de você o mínimo de respeito aos nossos princípios, 
            os quais são também uma forma de manter a credibilidade e a segurança da rede.
        </p>  
        <h4 style="margin-bottom: 20px;">
            <strong>1.1 Compromissos de Segurança</strong>
        </h4>
        <p id="texto_justificado">
            <strong>1.</strong> Publicações comerciais (como spam) na CapitalFuturo
            não são permitidas.           
        </p>  
        <p id="texto_justificado">
            <strong>2.</strong> 
            Você não tem permissão para coletar conteúdos ou informações de usuários, ou 
            acessar a CapitalFuturo, usando meios automatizados 
            (como bots de coleta, robôs, spiders ou scrapers) 
            sem nossa permissão prévia.
        </p>  
        <p id="texto_justificado">
            <strong>3.</strong> 
            Você não tem permissão para solicitar informações de login, 
            nem acessar uma conta que pertença a outra pessoa. A violação desse termo contribuirá
            para o seu banimento para sempre da CapitalFuturo, caso seja constatada a violação.
        </p>
        <p id="texto_justificado">
            <strong>4.</strong>
            Você não irá intimidar, assediar ou praticar bullying contra qualquer usuário sob nehuma circunstância. Caso 
            você viole este item, será banido da rede sem nenhum tipo de aviso prévio.
        </p>           
        <p id="texto_justificado">
            <strong>5.</strong>
            Você não usará a CapitalFuturo para praticar qualquer ato ilegal, equivocado, malicioso ou discriminatório. Caso 
            você viole este item, será banido da rede sem nenhum tipo de aviso prévio e poderá sofrer sanções penais se sua ação tiver que 
            ser informada as autoridades.
        </p>           
        <p id="texto_justificado">
            <strong>6.</strong>
            Você não facilitará nem incentivará a violação desta Declaração ou de nossas políticas.
        </p>           
        <p id="texto_justificado">
            <strong>7.</strong> 
            Se você for denunciado 3 vezes, ou se mais de 7 usuários 
            se manifestarem contra você em uma única denúncia e nossa análise constatar 
            que as denúncias são verdadeiras, seu perfil será bloqueado e você será 
            banido da CapitalFuturo para sempre.
        </p>           
        <p id="texto_justificado">
            <strong>8.</strong> 
            Nosso ambiente sempre colaborará com a justiça de nosso país. Então, esteja ciente de que se você usar os recursos de nossa
            rede para cometer qualquer que seja o ato ilegal e a justiça solicitar seus dados, os mesmos serão entregues as autoridades 
            competentes de pronto.
        </p>
    </div>					
</div>
<hr/>
<div class="row clearfix">
    <div class="col-md-12 column">          
        <h3 style="margin-bottom: 20px;">
            <strong>2. Alterações</strong>
        </h3>       
        <p id="texto_justificado" style="color: #f00">
                Nós reservamos o direito de alterar esses termos, bem como quaisquer termos relacionados aos nossos serviços a qualquer tempo.
        </p>
        <p id="texto_justificado">
            <strong>1.</strong> 
            Todos os usuários serão notificados sobre e quando ocorrerem atualizações
            nesse acordo, desta forma os mesmos podrão decidir se concordam e aderem ou não as mudanças, 
            ressaltando que se você não concorda com qualquer desses termos, não deve usar o ambiente CapitalFuturo.
        </p>          
        <p id="texto_justificado">
            <strong>2.</strong> 
            Caso ocorra qualquer alteração nesses termos ou em outros e 
            você continuae a usar nossos serviços, 
            significa que você aceitou as mudanças nos termos.
        </p>          
    </div>					
</div>
<hr/>
<div class="row clearfix">
    <div class="col-md-12 column">          
        <h3 style="margin-bottom: 20px;">
            <strong>3. Privacidade</strong>
        </h3>           
        <p id="texto_justificado">
            Sua privacidade em nosso ambiente funciona de acordo com nossa 
            Políticas de Dados, 
            recomendamos fortemente que você visite o item que trata da mesma para
            saber como seus dados são gerenciados.           
        </p>           
    </div>					
</div>
<hr/>
<div class="row clearfix">
    <div class="col-md-12 column">          
        <h3 style="margin-bottom: 20px;">
            <strong>4. Compartilhando suas informações e conteúdos</strong>
        </h3>           
        <p id="texto_justificado">
            Todas as informações e conteúdos 
            que você publica na CapitalFuturo são suas, a você é 
            reservado o direito de apagar todos os seus dados a quaquer tempo, ou a medida que 
            as condições técnicas do ambiente permitirem.
        </p>  
        <p id="texto_justificado">
            <strong>1.</strong> Nós respeitamos seus conteúdos de modo que 
            tudo aquilo advindo da sua propriedade intelectual 
            é seu, caso tenhamos interesse em algo, entraremos em contato com você
            para tentar viabilizar uma necociação boa para as partes, a você é 
            reservado o direito de aceitar ou não qualquer proposta que venha a receber pelo
            conteúdo que gerar.           
        </p>  
        <p id="texto_justificado">
            <strong>2.</strong> 
            Você é responsável pela forma como gerencia e compartilha seu conteúdo, 
            não nos responsabilizamos pelo uso que outros usuários possam 
            dar para as informações encontradas
            no seu perfil. No entanto, agiremos sempre quando recebermos qualquer denúncia de 
            de uso de dados que vá de de encontro a nossa política de dados.
        </p>  
        <p id="texto_justificado">
            <strong>3.</strong> 
            Quando sua conta é excluída, 
            seu conteúdo pode permanecer em cópias de 
            backup(inacessiveis para outros) por um tempo razoável.
        </p>
        <p id="texto_justificado">
            <strong>4.</strong>      
            Seus comentários ou outras sugestões sobre a CapitalFuturo 
            são sempre bem-vindos, mas entenda que podemos usar 
            esses comentários ou sugestões sem qualquer obrigação 
            de compensar você por eles (assim como você não 
            tem a obrigação de oferecê-los). Embora sua particição seja 
            uma prática que nós apreciamos, pois todos os usuários ganham 
            com melhorias advindas de sugestões, inclusive você.  
        </p>           
    </div>					
</div>
<hr/>
<div class="row clearfix">
    <div class="col-md-12 column">          
        <h3 style="margin-bottom: 20px;">
            <strong>5. Registro de Conta</strong>
        </h3>       
        <p id="texto_justificado">
            <strong>1.</strong> Você não tem permissão para fornecer qualquer informação 
            pessoal falsa na CapitalFuturo. E só pode criar um perfil mediante um convite de outro usuário.        
        </p>  
        <p id="texto_justificado">
            <strong>2.</strong> 
            Você poderá não poderá ter mais de uma conta pessoal.
        </p>  
        <p id="texto_justificado">
            <strong>3.</strong> 
            Caso sua conta seja desativada e você venha a criar outra sem nossa permissão, 
            você assumi o risco de ser processado pela violação desse acordo.
        </p>  
        <p id="texto_justificado">
            <strong>4.</strong> 
            Você não tem permissão para usar a CapitalFuturo se for menor de 14 anos.
        </p>  
        <p id="texto_justificado">
            <strong>5.</strong> 
            Sua conta é sua e sempre se manterá assim, não sendo possível transferir a mesma para outra pessoa.
            Você estará assumindo o risco de ser processado caso descumpra esse item.
        </p>        
    </div>					
</div>
<hr/>

<?php
//<div class="row clearfix">
//    <div class="col-md-12 column">          
//        <h3 style="margin-bottom: 20px;">
//            <strong>7. Disputas</strong>
//        </h3>       
//        <p id="texto_justificado" style="color: #f00">
//   
//                Item não definido ainda!
//    
//        </p>               
//    </div>					
//</div>
?>