<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Listagem de usuários por prioridade defiinida</h3>
            </div>
            <div class="box-body">
                <table id="users" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>Image</th>
                          <th>Nome</th>
                          <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($userData as $user) : ?>
                        <tr>
                          <td styel="background: #f00">
                              <img id="fotoperfil" src="<?= STATIC_URL_INTO.$user['fotoperfil']; ?>"
                              class="img-circle"
                              >
                          </td>
                          <td><?= $user["nome"]; ?></td>
                          <td>
                              <a href="<?=SITE_URL?>/usuario/verUsuario/<?=$user['email']?>"
                              class="btn btn-primary btn-sm">Visualizar Perfil</a>
                          </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Image</th>
                        <th>Nome</th>
                        <th></th>
                      </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<?php if (Geekx\Session::get("listUsersAdv")): ?>
    <?php Geekx\Session::delete("listUsersAdv"); ?>
<?php endif; ?>
