<script src="<?= STATIC_URL_INTO ?>/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/search_advanced.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/jquery-ui.min.js"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>


<script src="<?= STATIC_URL_INTO ?>/bootstrap/js/bootstrap.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/raphael-min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/morris/morris.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/sparkline/jquery.sparkline.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/knob/jquery.knob.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/moment.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/daterangepicker/daterangepicker.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/fastclick/fastclick.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/app.min.js"></script>
<!--<script src="<?= STATIC_URL_INTO ?>/dist/js/pages/dashboard.js"></script>-->
<script src="<?= STATIC_URL_INTO ?>/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= STATIC_URL_INTO ?>/plugins/datatables/dataTables.bootstrap.min.js"></script>

<script>
    $(function () {
        $("#users").DataTable({
            "language": {
                "url": "<?= STATIC_URL_INTO ?>/dist/json/Portuguese-Brasil.json"
            }
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });
</script>

<script src="<?= STATIC_URL_INTO ?>/plugins/jquery.form.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/funcoes_user.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/search_ind_page.js"></script>
<?php
/*
  |--------------------------------------------
  |Tem que estar presente em todos os arquivos
  |--------------------------------------------
 */
?>
<script src="<?= STATIC_URL_INTO ?>/dist/js/config.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/update_images.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/notifications.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/load_invest_prefs.js"></script>
<script src="<?= STATIC_URL_INTO ?>/dist/js/load_links_sociais.js"></script>
