<head>
    <meta charset="pt-br">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Capital|Futuro</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/dist/css/font-awesome-4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/dist/css/ionicons-2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/dist/css/skins/_all-skins.min.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/iCheck/flat/blue.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/morris/morris.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/jvectormap/jquery-jvectormap-1.2.2.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/datepicker/datepicker3.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/datatables/dataTables.bootstrap.css">    
    <link rel="stylesheet" href="<?= STATIC_URL_INTO ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">