<aside class="main-sidebar">
    <section class="sidebar">
        <form id="form-search" action="" method="post" class="sidebar-form">
            <div class="input-group">
                <input type="text"
                class="form-control"
                placeholder="Pesquisar..."
                id="busca"
                value="">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-flat btn-pesquisar">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">MENU DE NAVEGAÇÃO</li>
            <li>
                <a href="<?= SITE_URL; ?>/admin">
                    <i class="fa fa-group"></i>
                    <span>Usuários</span>
                </a>
            </li>
            <li>
                <a href="<?= SITE_URL; ?>/edAdmin">
                    <i class="fa  fa-graduation-cap"></i>
                    <span>Educacional</span>
                </a>
            </li>
             <li>
                <a href="">
                    <i class="fa  fa-paper-plane"></i>
                    <span>Chat</span>
                </a>
            </li>
        </ul>
    </section>
</aside>
