<aside class="main-sidebar">
    <section class="sidebar">
        <form id="form-search" action="" method="post" class="sidebar-form">
            <div class="input-group">
                <input type="text"
                       class="form-control"
                       placeholder="Pesquisar..."
                       id="busca"
                       value="">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-flat btn-pesquisar">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">MENU DE NAVEGAÇÃO</li>
            <li>
                <a href="<?= SITE_URL; ?>/admin">
                    <i class="fa fa-group"></i>
                    <span>Usuários</span>
                </a>
            </li>            
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Páginas</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?= SITE_URL; ?>/editdatapages/login"><i class="fa fa-shopping-cart"></i>Login</a></li>                                               
                </ul>
            </li>
        </ul>
    </section>
</aside>
