<!doctype html>
<html>

    <!-- head area open -->
    <?php $this->loadView("homes/home_one/partes/head"); ?>
    <!-- head area end -->

    <body>
        <!-- preloader area open -->
        <?php $this->loadView("homes/home_one/partes/preloader"); ?>
        <!-- preloader area end -->

        <!-- header area open -->
        <?php $this->loadView("homes/home_one/partes/header"); ?>
        <!-- header area end --> 

        <!-- slides area open -->
        <?php $this->loadView("homes/home_one/partes/slides"); ?>
        <!-- slides area end   -->

        <!-- service area open -->
        <?php $this->loadView("homes/home_one/partes/services"); ?>
        <!-- service area end   -->

        <!-- work area open -->
        <?php $this->loadView("homes/home_one/partes/works"); ?>
        <!-- work area end   -->

        <!--  getit area open -->
        <?php $this->loadView("homes/home_one/partes/barra_superior"); ?>
        <!--  getit area end -->

        <!-- portfolio area open -->
        <?php $this->loadView("homes/home_one/partes/portfolio"); ?>
        <!-- portfolio area end   -->

        <!-- skill area open -->
        <?php $this->loadView("homes/home_one/partes/skill"); ?>
        <!-- skill area end -->

        <!-- blog area open   -->
        <?php
        // $this->loadView("home/home_one/partes/blog"); 
        ?>
        <!-- blog area end   -->

        <!-- price area open   -->
        <?php
        // $this->loadView("home/home_one/partes/price"); 
        ?>
        <!-- price area end   -->

        <!-- testimonial area open   -->
        <?php // $this->loadView("home/home_one/partes/testimonial"); ?>
        <!-- testimonial area end   -->

        <!-- contact area open   -->
        <?php $this->loadView("homes/home_one/partes/contact"); ?>
        <!-- contact area end   -->

        <?php $this->loadView("homes/home_one/partes/js_footer"); ?>
    </body>
</html>
