-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 02:14:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema socialmedia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema socialmedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socialmedia` DEFAULT CHARACTER SET utf8 ;
USE `socialmedia` ;

-- -----------------------------------------------------
-- Table `socialmedia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(200) NOT NULL,
  `nascimento` DATE NULL,
  `minibio` TEXT NULL,
  `genero` INT NOT NULL,
  `fone` VARCHAR(100) NULL DEFAULT 'null',
  `status` TINYINT(1) NOT NULL DEFAULT true,
  `senha` CHAR(32) NOT NULL,
  `logado` TINYINT(1) NOT NULL DEFAULT false,
  `fotoperfil` VARCHAR(250) NOT NULL DEFAULT '/dist/img/into/image_default.jpg',
  `fotocapa` VARCHAR(250) NULL DEFAULT 'null',
  `datcad` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`usuario_tem_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`usuario_tem_usuario` (
  `usuario_anfitriao` INT UNSIGNED NOT NULL,
  `usuario_convidado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`usuario_anfitriao`, `usuario_convidado`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`usuario_convidado` ASC),
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`usuario_anfitriao` ASC),
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuario_anfitriao`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`usuario_convidado`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`convite` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email_anfitriao` VARCHAR(100) NOT NULL,
  `email_convidado` VARCHAR(100) NOT NULL,
  `convite` CHAR(32) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT false,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`chat` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_de` INT(11) NOT NULL,
  `id_para` INT(11) NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `time` INT(11) NOT NULL,
  `lido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`usuario_tem_convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`usuario_tem_convite` (
  `usuario_anfitriao` INT UNSIGNED NOT NULL,
  `usuario_convidado` INT UNSIGNED NOT NULL,
  `convite_id` INT UNSIGNED NOT NULL,
  INDEX `fk_usuario_has_convite_convite1_idx` (`convite_id` ASC),
  INDEX `fk_usuario_has_convite_usuario1_idx` (`usuario_convidado` ASC),
  CONSTRAINT `fk_usuario_has_convite_usuario1`
    FOREIGN KEY (`usuario_convidado`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_convite_convite1`
    FOREIGN KEY (`convite_id`)
    REFERENCES `socialmedia`.`convite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`convite_interno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`convite_interno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email_anfitriao` VARCHAR(100) NOT NULL,
  `email_convidado` VARCHAR(100) NOT NULL,
  `convite` CHAR(32) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT false,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`usuario_tem_convite_interno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`usuario_tem_convite_interno` (
  `usuario_anfitriao` INT UNSIGNED NOT NULL,
  `usuario_convidado` INT UNSIGNED NOT NULL,
  `convite_interno_id` INT UNSIGNED NOT NULL,
  INDEX `fk_usuario_has_convite_interno_usuario1_idx` (`usuario_anfitriao` ASC),
  INDEX `fk_usuario_tem_convite_interno_convite_interno1_idx` (`convite_interno_id` ASC),
  CONSTRAINT `fk_usuario_has_convite_interno_usuario1`
    FOREIGN KEY (`usuario_anfitriao`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tem_convite_interno_convite_interno1`
    FOREIGN KEY (`convite_interno_id`)
    REFERENCES `socialmedia`.`convite_interno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`bug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`bug` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bug` TEXT NOT NULL,
  `dat_bug` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`report_bug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`report_bug` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `bug_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_report_bug_bug1_idx` (`bug_id` ASC),
  CONSTRAINT `fk_report_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_bug_bug1`
    FOREIGN KEY (`bug_id`)
    REFERENCES `socialmedia`.`bug` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialmedia`.`social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia`.`social` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bitbucket` VARCHAR(250) NULL,
  `dropbox` VARCHAR(250) NULL,
  `facebook` VARCHAR(250) NULL,
  `flickr` VARCHAR(250) NULL,
  `foursquare` VARCHAR(250) NULL,
  `github` VARCHAR(250) NULL,
  `googleplus` VARCHAR(250) NULL,
  `instagram` VARCHAR(250) NULL,
  `linkedin` VARCHAR(250) NULL,
  `tumblr` VARCHAR(250) NULL,
  `twitter` VARCHAR(250) NULL,
  `vk` VARCHAR(250) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_social_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_social_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `socialmedia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
