<head>
    <meta charset="utf-8">
    <title>Capital|Futuro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Estilos -->
    <link href="<?= STATIC_URL ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= STATIC_URL ?>/css/style.css" rel="stylesheet">
    <link href="<?= STATIC_URL ?>/css/signin.css" rel="stylesheet">
    <link href="<?= STATIC_URL ?>/css/nav.css" rel="stylesheet">
   
    <!-- Scripts -->
    <script type="text/javascript" src="<?= STATIC_URL ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL ?>/js/page_load.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL ?>/js/send_pass.js"></script>
    
<!--    <link rel="shortcut icon" href="<?= STATIC_URL ?>/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="<?= STATIC_URL ?>/img/favicon.ico" type="image/x-icon">-->
</head>




