<div class="container-fluid footer" style="margin-top: 120px">
    <div class="clearfix">
        <div class="col-md-6 column">
            <p style="text-align: center; color: #333; padding-top: 22px; padding-bottom: 13px">          
                <a id="sobre" style="cursor: pointer">Sobre</a> | 
                <a id="termos" style="cursor: pointer">Termos</a> |
                <a id="politica" style="cursor: pointer">Política</a>
            </p>
        </div>
        <div class="col-md-6 column">
            <p style="text-align: center; color: #A9A9A9; 
               padding-top: 22px;
               padding-bottom: 13px">
                © 2017 - Copyleft
            </p>
        </div>
    </div>
</div>
