<?php
/*
  |--------------------------------
  |row - init
  |--------------------------------
 */
?>
<div class="row">
    <?php
    /*
      |--------------------------------
      |col - init
      |--------------------------------
     */
    ?>
    <section class="col-lg-8 connectedSortable">
        <?php
        /*
          |--------------------------------
          |box-success - init
          |--------------------------------
         */
        ?>         
        <div class="box box-danger">
            <?php
            /*
              |--------------------------------<-Deve ser preenchido via js!
              |boxheader - init
              |--------------------------------
             */
            ?>
            <div class="box-header" id="header-chat">


            </div>
            <?php
            /*
              |--------------------------------
              |boxheader - finish
              |--------------------------------
             */
            ?>
            <?php
            /*
              |================================<=Dever ser preenchido via js!
              |================================<=É onde os itens do chat são carregados!
              |========chat-box - init=========
              |================================
              |================================
             */
            ?>
            <div class="box-body chat" id="chat-box">

                <div class="col-md-12" style="text-align: center">
                    <h1 style="margin-bottom: 30px;">Olá!</h1>
                    <h4 style="margin-bottom: 30px;">
                        Para iniciar o chat use menu de acesso aos contatos a sua direita!
                    </h4>
                    <!--<p>
                        <a class="btn btn-danger btn-large" id="iniciar-chat">Inicar Chat</a>
                    </p>			-->
                </div>

            </div>
            <?php
            /*
              |================================
              |================================
              |=======chat-box - finish========
              |================================
              |================================
             */
            ?>
            <?php
            /*
              |--------------------------------<-Deve ser preenchido via js!
              |footer - init
              |--------------------------------
             */
            ?>
            <div class="box-footer" id="footer-chat">

            </div>
            <?php
            /*
              |--------------------------------
              |footer - finish
              |--------------------------------
             */
            ?>
        </div>
        <?php
        /*
          |--------------------------------
          |box-success - finish
          |--------------------------------
         */
        ?>
    </section>
    <?php
    /*
      |--------------------------------
      |col - finish
      |--------------------------------
     */
    ?>
</div>