<div class="modal fade modal-danger" id="errorSendMessage">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Erro interno!</h4>
            </div>
            <div class="modal-body">
                <p>Não foi possível enviar a mensagem!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Fechar</button>
                <!--<button type="button" class="btn btn-outline">Save changes</button>-->
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-danger" id="errorSendMessageBlank">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Erro interno!</h4>
            </div>
            <div class="modal-body">
                <p>Não é possível enviar uma mensagem em branco!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Fechar</button>
                <!--<button type="button" class="btn btn-outline">Save changes</button>-->
            </div>
        </div>
    </div>
</div>