<div class="blog_area">
  <div class="container">
    <div class="row">
      <div class="blog_section">
          <h1>Hot news from the <span>blog</span></h1>
          <div class="single_blog col-md-4 slider-content">
            <a href="#">
                <img src="img/1.jpg" alt="">
                <div class="slider-text">
                  <h3>This is demo title</h3>
                  <p> <i class="fa fa-user"></i> By FAHEM <i class="fa fa-clock-o"></i> August 31th, 2014</p>
                  <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.</p>
                </div>
            </a>
          </div> 
          <div class="single_blog col-md-4 slider-content">
            <a href="#">
                <img src="img/2.jpg" alt="">
                <div class="slider-text">
                  <h3>This is demo title</h3>
                  <p> <i class="fa fa-user"></i> By FAHEM <i class="fa fa-clock-o"></i> August 31th, 2014</p>                  
                  <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.</p>
                </div>
            </a>
          </div> 
          <div class="single_blog col-md-4 slider-content">
            <a href="#">
                <img src="img/3.jpg" alt="">
                <div class="slider-text">
                  <h3>This is demo title</h3>
                  <p> <i class="fa fa-user"></i> By FAHEM <i class="fa fa-clock-o"></i> August 31th, 2014</p>                  
                  <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.</p>
                </div>
            </a>
          </div>                              
      </div>
    </div>
  </div>
</div>