<!--<div class="contact_area">-->
<div class="testimonial_area">
    <div class="container">
        <div class="row" style="margin-bottom: 0px; padding-bottom: 0px">
            <div class="contact_section" style="text-align: center">
                <div class="col-md-12">
                    <h1 style="margin: 0px; padding: 0px">Contato</h1>       
                    <div class="contact_text">
                        <p></p>                                                                       
                    </div> 
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 0px; padding-top: 0px; padding-bottom: 40px">
            <div class="contact_section" style="margin-top: 0px; padding-top: 0px;">                 
                <div class="col-md-12">
                    <div class="contact_text" style="margin-top: 0px; padding: 0px">
                        <ul class="contact_info" style="text-align: center; padding: 0px; margin: 0px">
                            <li>capitalfuturo@club.com</li>
                            <li>capitalfuturo.parcerias@club.com</li>
                            <li>capitalfuturo.sugestoes@club.com</li>                          
                        </ul>                                                     
                    </div>
                </div>               
            </div>
        </div>
<!--        <div class="row">
            <div class="contact_section">
                <div class="col-md-12">
                    <ul class="contact_social" style="padding: 0px; margin: 0px; text-align: center">
                        <a href="#"><li><i class="fb fa fa-facebook-square"></i></li></a>
                        <a href="#"><li><i class="tw fa fa-twitter-square"></i></li></a>
                        <a href="#"><li><i class="rss fa fa-rss-square"></i></li></a>
                        <a href="#"><li><i class="gp fa fa-google-plus-square"></i></li></a>
                    </ul>  
                </div>
            </div>
        </div>-->
    </div> 
</div>