<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Capital|Futuro</title>

    <!--Google web fonts-->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,300italic,400italic,600,700,600italic,200,200italic' rel='stylesheet' type='text/css'>    
    <link href='http://fonts.googleapis.com/css?family=Play:400,700' rel='stylesheet' type='text/css'>
    
    <!-- Bootstrap -->
    <link href="<?= HOME_ONE ?>/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="<?= HOME_ONE ?>/css/animate.css">

    <!-- font awesome-->
    <!--<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="<?= HOME_ONE ?>/css/font-awesome-4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= HOME_ONE ?>/css/skillset.css">


    <link rel="stylesheet" type="text/css" href="<?= HOME_ONE ?>/css/owl.carousel.css"> 
    <link rel="stylesheet" type="text/css" href="<?= HOME_ONE ?>/css/owl.transitions.css">
    <link rel="stylesheet" type="text/css" href="<?= HOME_ONE ?>/css/owl.theme.css">

    <link rel="stylesheet" type="text/css" href="<?= HOME_ONE ?>/style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>