<header class="main_header">
  <div class="row">
    <div class="content"> <a class="logo" href="#">HOME</a>
      <div class="mobile-toggle"> <span></span> <span></span> <span></span></div>
      <nav>
        <ul class="main_menu">
          
          <li><a href=".service_area">Ferramentas</a></li>
          <li><a href=".portfolio_area">Publicados</a></li>
          <li><a href=".testimonial_area">Testemunhos</a></li>
          <li><a href=".contact_area">Contato</a></li>                    
        </ul>
      </nav>
    </div>
  </div>
</header>