
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?= HOME_ONE ?>/js/bootstrap.min.js"></script>
    
    <script src="<?= HOME_ONE ?>/js/wow.js"></script>

    <script src="<?= HOME_ONE ?>/js/jquery.nicescroll.js"></script>
    
    <script type="text/javascript" src="<?= HOME_ONE ?>/js/jquery.easing.min.js"></script>  
    <script type="text/javascript" src="<?= HOME_ONE ?>/js/jquery.mixitup.min.js"></script>
    <script src="<?= HOME_ONE ?>/js/imagesloaded.pkgd.min.js"></script>

   <script src="<?= HOME_ONE ?>/js/skillset.js"></script>

   <script src="<?= HOME_ONE ?>/js/owl.carousel.js"></script> 


   <script src="<?= HOME_ONE ?>/js/scrollupto.js"></script>
   <script type="text/javascript" src="<?= HOME_ONE ?>/js/main.js"></script>
   <script type="text/javascript" src="<?= HOME_ONE ?>/js/click_home.js"></script>