<div class="portfolio_area">
  <div class="container">
      <div class="portfolio_section">
          <div class="col-md-12 portfolio_top">
              <h1>Gratuitos</h1>
              <!--<p>OUR TEAM INCLUDES GREAT THINKERS. YOU WOULD LOVE TO WORK WITH THEM AS THEY ARE JUST AMAZING PEOPLE.</p>-->
          </div>  
      </div>

    <ul id="filters" class="clearfix">
      <li><span class="filter active" data-filter="app card icon logos web">Tudo</span></li>
      <!--<li><span class="filter" data-filter="app">Materiais</span></li>-->
      <!--<li><span class="filter" data-filter="app">App</span></li>-->
      <!--<li><span class="filter" data-filter="card">Card</span></li>
      <li><span class="filter" data-filter="icon">Icon</span></li>
      <li><span class="filter" data-filter="logos">Logo</span></li>
      <li><span class="filter" data-filter="web">Web</span></li>-->
    </ul>

    <div id="portfoliolist">
      
      <!--<div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">       
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/5.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Bird Document</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>        -->

      <div class="portfolio app" data-cat="app">
        <div class="portfolio-wrapper" id="m1">     
          <img src="<?= HOME_ONE ?>/img/portfolios/app/1.png" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title"></a>
              <span class="text-category">Renda fixa</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>    
      
      <!--<div class="portfolio web" data-cat="web">
        <div class="portfolio-wrapper">           
          <img src="<?= HOME_ONE ?>/img/portfolios/web/4.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Sonor's Design</a>
              <span class="text-category">Web design</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>        -->
      
      <!--<div class="portfolio card" data-cat="card">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/card/1.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Typography Company</a>
              <span class="text-category">Business card</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>  -->
            
      <div class="portfolio app" data-cat="app">
        <div class="portfolio-wrapper" id="m2">
          <img src="<?= HOME_ONE ?>/img/portfolios/app/3.png" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title"></a>
              <span class="text-category">Bancos</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>      
      
      <!--<div class="portfolio card" data-cat="card">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/card/4.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">BMF</a>
              <span class="text-category">Business card</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>  -->
      
      <!--<div class="portfolio card" data-cat="card">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/card/5.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Techlion</a>
              <span class="text-category">Business card</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>  -->
      
      <!--<div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/1.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">KittyPic</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                                                              -->
      
      <div class="portfolio app" data-cat="app">
        <div class="portfolio-wrapper" id="m3">     
          <img src="<?= HOME_ONE ?>/img/portfolios/app/2.png" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title"></a>
              <span class="text-category">Renda variável</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                            
      
      <!--<div class="portfolio card" data-cat="card">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/card/2.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">QR Quick Response</a>
              <span class="text-category">Business card</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>        -->

      <!--<div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/6.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Mobi Sock</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                  -->

      <!--<div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/7.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Village Community Church</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                          
      
      <div class="portfolio icon" data-cat="icon">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/icon/4.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Domino's Pizza</a>
              <span class="text-category">Icon</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>              -->

      <!--<div class="portfolio web" data-cat="web">
        <div class="portfolio-wrapper">           
          <img src="<?= HOME_ONE ?>/img/portfolios/web/3.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Backend Admin</a>
              <span class="text-category">Web design</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                                

      <div class="portfolio icon" data-cat="icon">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/icon/1.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Instagram</a>
              <span class="text-category">Icon</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>        -->
      
      <!--<div class="portfolio web" data-cat="web">
        <div class="portfolio-wrapper">           
          <img src="<?= HOME_ONE ?>/img/portfolios/web/2.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Student Guide</a>
              <span class="text-category">Web design</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                  

      <div class="portfolio icon" data-cat="icon">
        <div class="portfolio-wrapper">
          <img src="<?= HOME_ONE ?>/img/portfolios/icon/2.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Scoccer</a>
              <span class="text-category">Icon</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                                                                                                                

      <div class="portfolio icon" data-cat="icon">
        <div class="portfolio-wrapper">           
          <img src="<?= HOME_ONE ?>/img/portfolios/icon/5.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">3D Map</a>
              <span class="text-category">Icon</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>      
      
      <div class="portfolio web" data-cat="web">
        <div class="portfolio-wrapper">           
          <img src="<?= HOME_ONE ?>/img/portfolios/web/1.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Note</a>
              <span class="text-category">Web design</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                  
      
      <div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/3.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Native Designers</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                  

      <div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/4.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Bookworm</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                                        
      
      <div class="portfolio icon" data-cat="icon">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/icon/3.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Sandwich</a>
              <span class="text-category">Icon</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>                                                
      
      <div class="portfolio card" data-cat="card">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/card/3.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Reality</a>
              <span class="text-category">Business card</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>  

      <div class="portfolio logos" data-cat="logos">
        <div class="portfolio-wrapper">     
          <img src="<?= HOME_ONE ?>/img/portfolios/logo/2.jpg" alt="" />
          <div class="label">
            <div class="label-text">
              <a class="text-title">Speciallisterne</a>
              <span class="text-category">Logo</span>
            </div>
            <div class="label-bg"></div>
          </div>
        </div>
      </div>        -->
                    
      
    </div>
    
  </div>
</div>