<div class="price_area">
  <div class="container">
    <div class="row">
      <div class="price_section">
          <h1>Price section</h1>
              <div class="col-md-12">
                <div class="pricing-table">
                  <div class="col-md-4 col-sm-4 col-xs-12 pricing-box first wow bounceInUp animated">
                    <ul>
                      <li class="plan-title">
                        Silver
                      </li>
                      <li class="subscription-price oswald">
                        <span class="currency oswald">$</span>
                        <span class="price">59</span>
                        / mon
                      </li>
                      <li class="ptop10">
                        5 Free Websites
                      </li>
                      <li>
                        100 Gb Storage
                      </li>
                      <li>
                        24 / 7 Full Support
                      </li>
                      <li>
                        Cloud Backup
                      </li>
                      <li>
                        5 Admin Panels
                      </li>
                      <li>
                        Free Trials
                      </li>
                      <li class="last border-none pbottom40">
                        No Bonus Points
                      </li>
                      <li class="sing-up">
                        <a href="#" class="animate">Sign Up</a>
                      </li>
                    </ul>
                  </div><!-- end pricing-box -->
                  <div class="col-md-4 col-sm-4 col-xs-12 pricing-box second featured wow bounceInUp animated">
                    <ul>
                      <li class="plan-title">
                        Gold
                      </li>
                      <li class="subscription-price oswald">
                        <span class="currency oswald">$</span>
                        <span class="price">79</span>
                        / mon
                      </li>
                      <li class="ptop10">
                        20 Free Websites
                      </li>
                      <li>
                        500 Gb Storage
                      </li>
                      <li>
                        Full Support
                      </li>
                      <li>
                        Cloud Backup
                      </li>
                      <li>
                        20 Admin Panels
                      </li>
                      <li>
                        Free Trials
                      </li>
                      <li class="last border-none pbottom40">
                        All Bonus Points
                      </li>
                      <li class="sing-up">
                        <a href="#" class="animate">Sing Up</a>
                      </li>
                    </ul>
                  </div><!-- end pricing-box -->
                  <div class="col-md-4 col-sm-4 col-xs-12 pricing-box last wow bounceInUp animated">
                    <ul>
                      <li class="plan-title">
                        Diamond
                      </li>
                      <li class="subscription-price oswald">
                        <span class="currency oswald">$</span>
                        <span class="price">99</span>
                        / mon
                      </li>
                      <li class="ptop10">
                        50 Free Websites
                      </li>
                      <li>
                        1 Tb Storage
                      </li>
                      <li>
                        Full Support
                      </li>
                      <li>
                        Cloud Backup
                      </li>
                      <li>
                        50 Admin Panels
                      </li>
                      <li>
                        Free Trials
                      </li>
                      <li class="last border-none pbottom40">
                        All Bonus Points
                      </li>
                      <li class="sing-up">
                        <a href="#" class="animate">Sing Up</a>
                      </li>
                    </ul>
                  </div><!-- end pricing-box -->
                </div>
              </div>
          
      </div>
    </div>
  </div>
</div>