<div class="service_area">
  <div class="container">
    <div class="row">
      <div class="service_section wow bounceInLeft animated">
          <div class="col-md-12">
            <div class="single_service">        
              <div class="ico" id="social"><i class="fa fa-share-alt"></i></div>
              <h2>Social</h2>
              <p>Capital Futuro também é um ambiente social reservado a pessoas que querem entender um pouco mais do mundo das finanças.</p>
            </div>
          </div>

          <!--<div class="col-md-6">
            <div class="single_service">        
              <div class="ico" id="kalko"><i class="fa fa-mobile"></i></div>          
              <h2>Calko</h2>
              <p>É o nosso aplicativo de cálculo de juros compostos. Baixe direto do link ou da Google Play Store.</p>
            </div>
          </div>-->

          <!--<div class="col-md-3">
            <div class="single_service">        
              <div class="ico"><i class="fa fa-paint-brush"></i></div>         
              <h2>Superb design</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
              tempor incididunt ut labore</p>
            </div>
          </div>

          <div class="col-md-3">
            <div class="single_service">        
              <div class="ico"><i class="fa fa-heart-o"></i></div>        
              <h2>Made with love</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
              tempor incididunt ut labore</p>
            </div>
          </div>-->

      </div>
    </div>
  </div>
</div>