<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="2000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
        <hgroup>
            <h1>Capital|<span>Futuro</span></h1>        
            <h3>Crescendo junto com você!</h3>
        </hgroup>
        <!--<button class="btn btn-hero btn-lg" role="button">See all features</button>-->
      </div>
    </div>
    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero">        
        <hgroup>
            <h1>Aprenda a valorizar seu <span>dinheiro</span></h1>        
            <h3>Conheça nossos materiais gratuitos</h3>
        </hgroup>       
        <!--<button class="btn btn-hero btn-lg" role="button">Get Start</button>-->
      </div>
    </div>
    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero">        
        <hgroup>
            <h1>Comunique-<span>se</span></h1>        
            <h3>Troque ideias com outros investidores</h3>
        </hgroup>
        <a class="btn btn-hero btn-lg" href="http://localhost/mindmon$/login" role="button">Get Club</a>
      </div>
    </div>
  </div> 
</div>