<div class="testimonial_area">
  <div class="container">
    <div class="row">
      <div class="testimonial_section">
          <h1>O quê <span>as pessoas dizem</span></h1>
                        <div id="testimonial_carosule" class="owl-carousel owl-theme">
                            <div class="item"> 
                               <blockquote>
                               <img src="<?= HOME_ONE ?>/img/tm1.png"> 
                               <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                </p>      
                              </blockquote>  
                              <h3>----  kopa Samsu || Kopa Master</h3>                    
                            
                            </div> 
                            <div class="item"> 
                               <blockquote>
                               <img src="<?= HOME_ONE ?>/img/tm1.png"> 
                               <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                </p>      
                              </blockquote>  
                              <h3>----  Kuddus boyati || Baula</h3>                    
                            
                            </div> 
                            <div class="item"> 
                               <blockquote>
                               <img src="<?= HOME_ONE ?>/img/tm1.png"> 
                               <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                </p>      
                              </blockquote>  
                              <h3>----  Rohima || Kamner Beti</h3>                    
                            
                            </div> 
                            <div class="item"> 
                               <blockquote>
                               <img src="<?= HOME_ONE ?>/img/tm1.png"> 
                               <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                </p>      
                              </blockquote>  
                              <h3>----  Khairun sundori || Laika</h3>                    
                            
                            </div>                                                                          
                        </div>          
      </div>
    </div>
  </div>
</div>