<div class="work_area">
  <div class="container">
    <div class="row">  
      <div class="work_section">
        <h1 class="wow bounceInLeft">Processo funcional de<span> trabalho</span></h1>
          <div class="col-md-12 wow bounceInRight animated">
            <div class="bs-example">
              <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#sectionA"><i class="fa fa-lightbulb-o"></i></a></li>
                  <li><a data-toggle="tab" href="#sectionB"><i class="fa fa-compass"></i></a></li>
                  <!--<li><a data-toggle="tab" href="#sectionC"><i class="fa fa-cogs"></i></a></li>
                  <li><a data-toggle="tab" href="#sectionD"><i class="fa fa-paper-plane"></i></a></li>
                  <li><a data-toggle="tab" href="#sectionE"><i class="fa fa-line-chart"></i></a></li>-->
              </ul>
              <div class="tab-content">
                  <div id="sectionA" class="tab-pane fade in active">
                      <h3>Estratégia</h3>
                      <p>Nossa estratégia diz respeito a fomentar o engajamento com aspectos fundamentais do mercado financeiro.</p>
                  </div>
                  <div id="sectionB" class="tab-pane fade">
                      <h3>Plano</h3>
                      <p>Diz respeito a produzir a maior quantidade de conteúdo sobre finanças acessível ao público.</p>
                  </div>
                  <!--<div id="sectionC" class="tab-pane fade">
                      <h3>Mechanism</h3>
                      <p>Vestibulum nec erat eu nulla rhoncus fringilla ut non neque. Vivamus nibh urna, ornare id gravida ut, mollis a magna. Aliquam porttitor condimentum nisi, eu viverra ipsum porta ut. Nam hendrerit bibendum turpis, sed molestie mi fermentum id. Aenean volutpat velit sem. Sed consequat ante in rutrum convallis. Nunc facilisis leo at faucibus adipiscing.</p>
                  </div>
                  <div id="sectionD" class="tab-pane fade">
                      <h3>Title</h3>
                      <p>Vestibulum nec erat eu nulla rhoncus fringilla ut non neque. Vivamus nibh urna, ornare id gravida ut, mollis a magna. Aliquam porttitor condimentum nisi, eu viverra ipsum porta ut. Nam hendrerit bibendum turpis, sed molestie mi fermentum id. Aenean volutpat velit sem. Sed consequat ante in rutrum convallis. Nunc facilisis leo at faucibus adipiscing.</p>
                  </div>
                  <div id="sectionE" class="tab-pane fade">
                      <h3>Workflow</h3>
                      <p>Vestibulum nec erat eu nulla rhoncus fringilla ut non neque. Vivamus nibh urna, ornare id gravida ut, mollis a magna. Aliquam porttitor condimentum nisi, eu viverra ipsum porta ut. Nam hendrerit bibendum turpis, sed molestie mi fermentum id. Aenean volutpat velit sem. Sed consequat ante in rutrum convallis. Nunc facilisis leo at faucibus adipiscing.</p>
                  </div>                                                -->
              </div>
            </div>
          </div>
      </div>
    </div>  
  </div>    
</div>