<div class="row">
    <div class="col-md-8">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Categorias</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body no-padding">
                <ul class="users-list clearfix">
                    <?php foreach($categorias as $categoria):?>
                    <li>
                        <a class="btn btn-app" href="<?= SITE_URL; ?>/Ed2/listarConteudoPorCategoria/<?= $categoria['categoria']?>">
                            <i class="fa fa-contao"></i><?= $categoria['categoria']?>
                        </a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
</div>