<select name="mes" class="form-control" required="true"
        style="width: 100px; float: left">
    <option value="0" selected="1">Mês</option>
    <option value="1">Jan</option>
    <option value="2">Fev</option>
    <option value="3">Mar</option>
    <option value="4">Abr</option>
    <option value="5">Maio</option>
    <option value="6">Jun</option>
    <option value="7">Jul</option>
    <option value="8">Ago</option>
    <option value="9">Set</option>
    <option value="10">Out</option>
    <option value="11">Nov</option>
    <option value="12">Dez</option>
</select>